version: '2'
services:
    app:
        restart: always
        container_name: mediawiki
        build: 
            context: ./dockerfiles/
            dockerfile: app.docker
        volumes:
            - ./mediawiki:/var/www/html
        depends_on:
            - db
    db:
        restart: always
        container_name: mediawiki-db
        image: mysql
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "pass"
            MYSQL_DATABASE: "my_wiki"
    nginx:
        restart: always
        container_name: mediawiki-nginx
        build:
            context: ./dockerfiles/
            dockerfile: nginx.docker
        ports:
            - "80:80"
        volumes_from:
            - app
