version: '2'
services:
    app:
        restart: always
        container_name: mediawiki
        build: 
            context: ./dockerfiles/
            dockerfile: app.docker
        volumes:
            - ./mediawiki:/var/www/html
        depends_on:
            - db
    db:
        restart: always
        container_name: mediawiki-db
        image: mysql:5.7
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "my_wiki"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    nginx:
        restart: always
        container_name: mediawiki-nginx
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - app
